### ISSUE TITLE
Server Tick Loop Error

### ISSUE THREAD

**Issue by AdmiralEinstein** [Gamealition/Opis#1] opened 2015-12-01 23:08 UTC
I Installed Opis on the server and it failed to boot, here is the crash report.
[crash-2015-12-01_18.02.37-server.txt](https://github.com/Gamealition/Opis/files/49173/crash-2015-12-01_18.02.37-server.txt)

**Comment by RoyCurtis** [comment] 2015-12-01 23:26
Thank you for reporting this. This does not look like an easy crash to figure out.

I will have to find time to look into it, but I have some questions meanwhile:

* I notice this is a Cauldron server. Have you ever had other versions of Opis working on Cauldron?
    * If not, will you be willing to make a copy of your server without Cauldron (just plain forge) and try it with Opis? Does it crash the same way?
* What modpack is this?

**Comment by AdmiralEinstein** [comment] 2015-12-01 23:41
Current pack is Infinity 2.1.3
Yes we had Opis running on the version we were running before which was.... 2.0.2 I believe. We used a fixed version of mobius core from Yive, https://github.com/TCPR/Fixes

I can try a plain forge server in a while, can't right at this moment.
And thanks for the fast response!

**Comment by RoyCurtis** [comment] 2015-12-02 09:58
Unfortunately, I have been unable to use Prototik's patch to MobiusCore. The patch itself applies fine, but attempting to build using `gradle build` results in the following: https://gist.github.com/RoyCurtis/123eb171055edaed1b37

I have tried this with clean workspaces. I do not know what the problem is. I have a feeling it stems from updating the forge version used in my fork.

I do not feel like further perusing this issue as I do not wish to spend time supporting KCauldron. I am open to any help on this issue, however.

Here are the branches in which I have attempted to apply the patch:

* https://github.com/Gamealition/Opis/tree/mapless-kcfix
* https://github.com/Gamealition/MobiusCore/tree/modless-kcfix

Sorry. Maybe I will look into it another time. I have been thinking about re-doing the entire fork to make it backwards compatible with previous versions of Opis clients, and part of that may include not updating the Forge version used. I will keep the issue open, meanwhile.

**Comment by PhanaticD** [comment] 2015-12-03 01:46
I hope this can be fixed, I was just about to report the same thing

**Comment by Eidelmaim** [comment] 2016-01-10 00:59
Hey RoyCurtis have you seen someone has done a mobiuscore for Kcauldron 1.2.5, check it here, https://github.com/TCPR/Fixes/tree/master/KCauldron-MobiusCore-(Build-157%2B) figure you might be able to use this in trying to resolve this problem

**Comment by RoyCurtis** [comment] 2016-01-10 02:13
Thank you; however that appears to be the same patch I had tried (and failed) to apply

**Comment by Eidelmaim** [comment] 2016-01-10 02:47
this might be usefull.. it has been updated 27 days ago... much newer? than the attempt you tried ?

**Comment by RoyCurtis** [comment] 2016-01-10 03:05
It is the same. The linked repository is new and only contains a jar which does not indicate that it is using new patch code. I believe it is using the same version and code originally from https://gitlab.prok.pw/KCauldron/KCauldron-MobiusCore , which was last updated 3 months ago.

**Comment by Eidelmaim** [comment] 2016-01-10 03:24
ahh makes sense, we have our plugin/mods devs pulling your repos and seeing if the can help find a solution. ill let you know if we come across anything, this would be really usefull with updated kcauldron servers

**Comment by RoyCurtis** [comment] 2016-01-10 03:29
Really cool, thanks! I hope it goes well with you guys

**Comment by spannerman79** [comment] 2016-02-03 05:35
Check the PR's - there was a pull request down in order for kcauldron compatibility.

**Comment by RoyCurtis** [comment] 2016-02-03 06:12
@AdmiralEinstein, @Eidelmaim, can you please confirm that 1.3.1 now works for you? https://github.com/Gamealition/Opis/releases/tag/1.3.1

**Comment by Eidelmaim** [comment] 2016-02-04 20:57
testing it right now... will reply with results

**Comment by Eidelmaim** [comment] 2016-02-04 21:10
ok, so far it is working.... it has however just crashed my client when i teleported to a entity... checking the crash reports now

**Comment by Eidelmaim** [comment] 2016-02-04 21:12
ok so the crash appears to have to do with crossing dimensions... specifically to dimension 6, being the dream world of witchery, may just have been a single time glitch, will test further crossing other dimensions

**Comment by Eidelmaim** [comment] 2016-02-04 21:14
if i remember correctly though.... we had this same issue with other versions of opis as well... it does not like sending you across domensions... we always had to manually ./mvtp to that DIM than us opis to goto the entity in question

**Comment by Eidelmaim** [comment] 2016-02-04 21:15
FYI... we are running Kcauldron 1614 UNOFFICIAL - and opis is working.

**Comment by RoyCurtis** [comment] 2016-02-05 01:17
@Eidelmaim Interesting; can you share the crash log please? I'd like to [check the original Opis bug tracker for that crash](https://bitbucket.org/ProfMobius/opis/issues). Maybe I can try to fix it for you in a new issue report.

Either way, I will take your word that this is otherwise working for Cauldron, and close this issue.

@Prototik: Thank you very much for the fix, once again. Out of curiosity, do you know what I did wrong when I attempted to apply the patch?

**Closed by RoyCurtis** 2016-02-05 01:17 UTC
Labels: bug, help wanted

**Comment by Eidelmaim** [comment] 2016-02-05 08:29
@RoyCurtis http://pastebin.com/PwGbmdtu this is the crash report
